---
title: "hw03"
author: "Sierra Park"
date: "10/5/2017"
output: github_document
---

```{r}
library(dplyr)
library(ggplot2)
```


```{r}
getwd()
roster <- read.csv("data/nba2017-roster.csv")
stats <- read.csv("data/nba2017-stats.csv")
stats
```


```{r}
stats <- mutate(stats,
  "missed_fg" = stats$"field_goals_atts" - stats$"field_goals_made",
  "missed_ft" = stats$"field_goals_atts" - stats$"field_goals_made",
  points = 3*stats$"points3_made" + 2*stats$"points2_made" + stats$"points1_made",
  rebounds = stats$"off_rebounds" + stats$"def_rebounds"
 )


stats <- mutate(stats,
    efficiency = (stats$points + stats$rebounds + stats$assists + stats$steals + stats$blocks - stats$"missed_fg" - stats$"missed_ft" - stats$turnovers)/stats$"games_played")

stats
```


```{r}
sink("output/efficiency-summary.txt")
summary(stats$efficiency)
sink()
```


```{r}
a <- merge(roster, stats)
a
```


```{r}
b <- aggregate(a$experience, by = list(team = a$team), FUN = mean)
b$x

teams <- aggregate(a[,c("experience","salary", "points3_atts", "points2_atts", "points1_atts", "off_rebounds", "def_rebounds", "assists", "steals", "blocks", "turnovers", "fouls", "efficiency")], by = list(team = a$team), FUN = sum)

teams$experience <- round(b$x,2)
teams$salary <- round(teams$salary/1000000,2)
teams
```


```{r}

```








